// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph_replication.proto

#include "graph_replication.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace meta {
PROTOBUF_CONSTEXPR RaftRequest::RaftRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wb_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_.wb_kind_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RaftRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftRequestDefaultTypeInternal() {}
  union {
    RaftRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftRequestDefaultTypeInternal _RaftRequest_default_instance_;
PROTOBUF_CONSTEXPR RaftMessage::RaftMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.graph_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RaftMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftMessageDefaultTypeInternal() {}
  union {
    RaftMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftMessageDefaultTypeInternal _RaftMessage_default_instance_;
PROTOBUF_CONSTEXPR RaftNodeInfo::RaftNodeInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.graph_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.node_id_)*/uint64_t{0u}
  , /*decltype(_impl_.bolt_port_)*/0
  , /*decltype(_impl_.raft_poft_)*/0
  , /*decltype(_impl_.is_leader_)*/false
  , /*decltype(_impl_.is_learner_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RaftNodeInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftNodeInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftNodeInfoDefaultTypeInternal() {}
  union {
    RaftNodeInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftNodeInfoDefaultTypeInternal _RaftNodeInfo_default_instance_;
PROTOBUF_CONSTEXPR RaftNodeInfos_NodesEntry_DoNotUse::RaftNodeInfos_NodesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    RaftNodeInfos_NodesEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal _RaftNodeInfos_NodesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR RaftNodeInfos::RaftNodeInfos(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.nodes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RaftNodeInfosDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftNodeInfosDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftNodeInfosDefaultTypeInternal() {}
  union {
    RaftNodeInfos _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftNodeInfosDefaultTypeInternal _RaftNodeInfos_default_instance_;
}  // namespace meta
static ::_pb::Metadata file_level_metadata_graph_5freplication_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_graph_5freplication_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_graph_5freplication_2eproto = nullptr;

const uint32_t TableStruct_graph_5freplication_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::meta::RaftRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::meta::RaftRequest, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftRequest, _impl_.wb_kind_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftRequest, _impl_.wb_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::meta::RaftMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::meta::RaftMessage, _impl_.graph_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftMessage, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.node_id_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.bolt_port_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.raft_poft_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.is_leader_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.is_learner_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfo, _impl_.graph_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos_NodesEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos_NodesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos_NodesEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos_NodesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::meta::RaftNodeInfos, _impl_.nodes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::meta::RaftRequest)},
  { 9, -1, -1, sizeof(::meta::RaftMessage)},
  { 17, -1, -1, sizeof(::meta::RaftNodeInfo)},
  { 30, 38, -1, sizeof(::meta::RaftNodeInfos_NodesEntry_DoNotUse)},
  { 40, -1, -1, sizeof(::meta::RaftNodeInfos)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::meta::_RaftRequest_default_instance_._instance,
  &::meta::_RaftMessage_default_instance_._instance,
  &::meta::_RaftNodeInfo_default_instance_._instance,
  &::meta::_RaftNodeInfos_NodesEntry_DoNotUse_default_instance_._instance,
  &::meta::_RaftNodeInfos_default_instance_._instance,
};

const char descriptor_table_protodef_graph_5freplication_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027graph_replication.proto\022\004meta\032\nraft.pr"
  "oto\"Q\n\013RaftRequest\022\n\n\002id\030\001 \001(\004\022%\n\007wb_kin"
  "d\030\002 \001(\0162\024.meta.WriteBatchKind\022\017\n\007wb_data"
  "\030\003 \001(\014\">\n\013RaftMessage\022\r\n\005graph\030\001 \001(\t\022 \n\007"
  "message\030\002 \001(\0132\017.raftpb.Message\"\207\001\n\014RaftN"
  "odeInfo\022\017\n\007node_id\030\001 \001(\004\022\n\n\002ip\030\002 \001(\t\022\021\n\t"
  "bolt_port\030\003 \001(\005\022\021\n\traft_poft\030\004 \001(\005\022\021\n\tis"
  "_leader\030\005 \001(\010\022\022\n\nis_learner\030\006 \001(\010\022\r\n\005gra"
  "ph\030\007 \001(\t\"\200\001\n\rRaftNodeInfos\022-\n\005nodes\030\001 \003("
  "\0132\036.meta.RaftNodeInfos.NodesEntry\032@\n\nNod"
  "esEntry\022\013\n\003key\030\001 \001(\004\022!\n\005value\030\002 \001(\0132\022.me"
  "ta.RaftNodeInfo:\0028\001*U\n\016WriteBatchKind\022\013\n"
  "\007UNKNOWN\020\000\022\017\n\013GRAPH_WRITE\020\001\022\020\n\014ID_GENERA"
  "TOR\020\002\022\023\n\017GRAPH_INDEX_DDL\020\003b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_graph_5freplication_2eproto_deps[1] = {
  &::descriptor_table_raft_2eproto,
};
static ::_pbi::once_flag descriptor_table_graph_5freplication_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_graph_5freplication_2eproto = {
    false, false, 554, descriptor_table_protodef_graph_5freplication_2eproto,
    "graph_replication.proto",
    &descriptor_table_graph_5freplication_2eproto_once, descriptor_table_graph_5freplication_2eproto_deps, 1, 5,
    schemas, file_default_instances, TableStruct_graph_5freplication_2eproto::offsets,
    file_level_metadata_graph_5freplication_2eproto, file_level_enum_descriptors_graph_5freplication_2eproto,
    file_level_service_descriptors_graph_5freplication_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_graph_5freplication_2eproto_getter() {
  return &descriptor_table_graph_5freplication_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_graph_5freplication_2eproto(&descriptor_table_graph_5freplication_2eproto);
namespace meta {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WriteBatchKind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_graph_5freplication_2eproto);
  return file_level_enum_descriptors_graph_5freplication_2eproto[0];
}
bool WriteBatchKind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class RaftRequest::_Internal {
 public:
};

RaftRequest::RaftRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:meta.RaftRequest)
}
RaftRequest::RaftRequest(const RaftRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RaftRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wb_data_){}
    , decltype(_impl_.id_){}
    , decltype(_impl_.wb_kind_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.wb_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.wb_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_wb_data().empty()) {
    _this->_impl_.wb_data_.Set(from._internal_wb_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.wb_kind_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.wb_kind_));
  // @@protoc_insertion_point(copy_constructor:meta.RaftRequest)
}

inline void RaftRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wb_data_){}
    , decltype(_impl_.id_){uint64_t{0u}}
    , decltype(_impl_.wb_kind_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.wb_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.wb_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RaftRequest::~RaftRequest() {
  // @@protoc_insertion_point(destructor:meta.RaftRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RaftRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.wb_data_.Destroy();
}

void RaftRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RaftRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:meta.RaftRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wb_data_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.wb_kind_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.wb_kind_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RaftRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .meta.WriteBatchKind wb_kind = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_wb_kind(static_cast<::meta::WriteBatchKind>(val));
        } else
          goto handle_unusual;
        continue;
      // bytes wb_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_wb_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RaftRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:meta.RaftRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // .meta.WriteBatchKind wb_kind = 2;
  if (this->_internal_wb_kind() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_wb_kind(), target);
  }

  // bytes wb_data = 3;
  if (!this->_internal_wb_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_wb_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meta.RaftRequest)
  return target;
}

size_t RaftRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:meta.RaftRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes wb_data = 3;
  if (!this->_internal_wb_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_wb_data());
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  // .meta.WriteBatchKind wb_kind = 2;
  if (this->_internal_wb_kind() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_wb_kind());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RaftRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RaftRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RaftRequest::GetClassData() const { return &_class_data_; }


void RaftRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RaftRequest*>(&to_msg);
  auto& from = static_cast<const RaftRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meta.RaftRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_wb_data().empty()) {
    _this->_internal_set_wb_data(from._internal_wb_data());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_wb_kind() != 0) {
    _this->_internal_set_wb_kind(from._internal_wb_kind());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RaftRequest::CopyFrom(const RaftRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meta.RaftRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RaftRequest::IsInitialized() const {
  return true;
}

void RaftRequest::InternalSwap(RaftRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.wb_data_, lhs_arena,
      &other->_impl_.wb_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RaftRequest, _impl_.wb_kind_)
      + sizeof(RaftRequest::_impl_.wb_kind_)
      - PROTOBUF_FIELD_OFFSET(RaftRequest, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RaftRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_graph_5freplication_2eproto_getter, &descriptor_table_graph_5freplication_2eproto_once,
      file_level_metadata_graph_5freplication_2eproto[0]);
}

// ===================================================================

class RaftMessage::_Internal {
 public:
  static const ::raftpb::Message& message(const RaftMessage* msg);
};

const ::raftpb::Message&
RaftMessage::_Internal::message(const RaftMessage* msg) {
  return *msg->_impl_.message_;
}
void RaftMessage::clear_message() {
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
}
RaftMessage::RaftMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:meta.RaftMessage)
}
RaftMessage::RaftMessage(const RaftMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RaftMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.graph_){}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.graph_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.graph_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_graph().empty()) {
    _this->_impl_.graph_.Set(from._internal_graph(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_message()) {
    _this->_impl_.message_ = new ::raftpb::Message(*from._impl_.message_);
  }
  // @@protoc_insertion_point(copy_constructor:meta.RaftMessage)
}

inline void RaftMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.graph_){}
    , decltype(_impl_.message_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.graph_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.graph_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RaftMessage::~RaftMessage() {
  // @@protoc_insertion_point(destructor:meta.RaftMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RaftMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.graph_.Destroy();
  if (this != internal_default_instance()) delete _impl_.message_;
}

void RaftMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RaftMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:meta.RaftMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.graph_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.message_ != nullptr) {
    delete _impl_.message_;
  }
  _impl_.message_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RaftMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string graph = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_graph();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "meta.RaftMessage.graph"));
        } else
          goto handle_unusual;
        continue;
      // .raftpb.Message message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_message(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RaftMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:meta.RaftMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string graph = 1;
  if (!this->_internal_graph().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_graph().data(), static_cast<int>(this->_internal_graph().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "meta.RaftMessage.graph");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_graph(), target);
  }

  // .raftpb.Message message = 2;
  if (this->_internal_has_message()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::message(this),
        _Internal::message(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meta.RaftMessage)
  return target;
}

size_t RaftMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:meta.RaftMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string graph = 1;
  if (!this->_internal_graph().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_graph());
  }

  // .raftpb.Message message = 2;
  if (this->_internal_has_message()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.message_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RaftMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RaftMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RaftMessage::GetClassData() const { return &_class_data_; }


void RaftMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RaftMessage*>(&to_msg);
  auto& from = static_cast<const RaftMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meta.RaftMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_graph().empty()) {
    _this->_internal_set_graph(from._internal_graph());
  }
  if (from._internal_has_message()) {
    _this->_internal_mutable_message()->::raftpb::Message::MergeFrom(
        from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RaftMessage::CopyFrom(const RaftMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meta.RaftMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RaftMessage::IsInitialized() const {
  return true;
}

void RaftMessage::InternalSwap(RaftMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.graph_, lhs_arena,
      &other->_impl_.graph_, rhs_arena
  );
  swap(_impl_.message_, other->_impl_.message_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RaftMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_graph_5freplication_2eproto_getter, &descriptor_table_graph_5freplication_2eproto_once,
      file_level_metadata_graph_5freplication_2eproto[1]);
}

// ===================================================================

class RaftNodeInfo::_Internal {
 public:
};

RaftNodeInfo::RaftNodeInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:meta.RaftNodeInfo)
}
RaftNodeInfo::RaftNodeInfo(const RaftNodeInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RaftNodeInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.graph_){}
    , decltype(_impl_.node_id_){}
    , decltype(_impl_.bolt_port_){}
    , decltype(_impl_.raft_poft_){}
    , decltype(_impl_.is_leader_){}
    , decltype(_impl_.is_learner_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.graph_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.graph_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_graph().empty()) {
    _this->_impl_.graph_.Set(from._internal_graph(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.node_id_, &from._impl_.node_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_learner_) -
    reinterpret_cast<char*>(&_impl_.node_id_)) + sizeof(_impl_.is_learner_));
  // @@protoc_insertion_point(copy_constructor:meta.RaftNodeInfo)
}

inline void RaftNodeInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.graph_){}
    , decltype(_impl_.node_id_){uint64_t{0u}}
    , decltype(_impl_.bolt_port_){0}
    , decltype(_impl_.raft_poft_){0}
    , decltype(_impl_.is_leader_){false}
    , decltype(_impl_.is_learner_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.graph_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.graph_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RaftNodeInfo::~RaftNodeInfo() {
  // @@protoc_insertion_point(destructor:meta.RaftNodeInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RaftNodeInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_.Destroy();
  _impl_.graph_.Destroy();
}

void RaftNodeInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RaftNodeInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:meta.RaftNodeInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  _impl_.graph_.ClearToEmpty();
  ::memset(&_impl_.node_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_learner_) -
      reinterpret_cast<char*>(&_impl_.node_id_)) + sizeof(_impl_.is_learner_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RaftNodeInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 node_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.node_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string ip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "meta.RaftNodeInfo.ip"));
        } else
          goto handle_unusual;
        continue;
      // int32 bolt_port = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.bolt_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 raft_poft = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.raft_poft_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_leader = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.is_leader_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_learner = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.is_learner_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string graph = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_graph();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "meta.RaftNodeInfo.graph"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RaftNodeInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:meta.RaftNodeInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 node_id = 1;
  if (this->_internal_node_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_node_id(), target);
  }

  // string ip = 2;
  if (!this->_internal_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "meta.RaftNodeInfo.ip");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_ip(), target);
  }

  // int32 bolt_port = 3;
  if (this->_internal_bolt_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_bolt_port(), target);
  }

  // int32 raft_poft = 4;
  if (this->_internal_raft_poft() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_raft_poft(), target);
  }

  // bool is_leader = 5;
  if (this->_internal_is_leader() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_is_leader(), target);
  }

  // bool is_learner = 6;
  if (this->_internal_is_learner() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_is_learner(), target);
  }

  // string graph = 7;
  if (!this->_internal_graph().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_graph().data(), static_cast<int>(this->_internal_graph().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "meta.RaftNodeInfo.graph");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_graph(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meta.RaftNodeInfo)
  return target;
}

size_t RaftNodeInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:meta.RaftNodeInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 2;
  if (!this->_internal_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // string graph = 7;
  if (!this->_internal_graph().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_graph());
  }

  // uint64 node_id = 1;
  if (this->_internal_node_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_node_id());
  }

  // int32 bolt_port = 3;
  if (this->_internal_bolt_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_bolt_port());
  }

  // int32 raft_poft = 4;
  if (this->_internal_raft_poft() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_raft_poft());
  }

  // bool is_leader = 5;
  if (this->_internal_is_leader() != 0) {
    total_size += 1 + 1;
  }

  // bool is_learner = 6;
  if (this->_internal_is_learner() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RaftNodeInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RaftNodeInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RaftNodeInfo::GetClassData() const { return &_class_data_; }


void RaftNodeInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RaftNodeInfo*>(&to_msg);
  auto& from = static_cast<const RaftNodeInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meta.RaftNodeInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (!from._internal_graph().empty()) {
    _this->_internal_set_graph(from._internal_graph());
  }
  if (from._internal_node_id() != 0) {
    _this->_internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_bolt_port() != 0) {
    _this->_internal_set_bolt_port(from._internal_bolt_port());
  }
  if (from._internal_raft_poft() != 0) {
    _this->_internal_set_raft_poft(from._internal_raft_poft());
  }
  if (from._internal_is_leader() != 0) {
    _this->_internal_set_is_leader(from._internal_is_leader());
  }
  if (from._internal_is_learner() != 0) {
    _this->_internal_set_is_learner(from._internal_is_learner());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RaftNodeInfo::CopyFrom(const RaftNodeInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meta.RaftNodeInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RaftNodeInfo::IsInitialized() const {
  return true;
}

void RaftNodeInfo::InternalSwap(RaftNodeInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_, lhs_arena,
      &other->_impl_.ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.graph_, lhs_arena,
      &other->_impl_.graph_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RaftNodeInfo, _impl_.is_learner_)
      + sizeof(RaftNodeInfo::_impl_.is_learner_)
      - PROTOBUF_FIELD_OFFSET(RaftNodeInfo, _impl_.node_id_)>(
          reinterpret_cast<char*>(&_impl_.node_id_),
          reinterpret_cast<char*>(&other->_impl_.node_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RaftNodeInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_graph_5freplication_2eproto_getter, &descriptor_table_graph_5freplication_2eproto_once,
      file_level_metadata_graph_5freplication_2eproto[2]);
}

// ===================================================================

RaftNodeInfos_NodesEntry_DoNotUse::RaftNodeInfos_NodesEntry_DoNotUse() {}
RaftNodeInfos_NodesEntry_DoNotUse::RaftNodeInfos_NodesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void RaftNodeInfos_NodesEntry_DoNotUse::MergeFrom(const RaftNodeInfos_NodesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata RaftNodeInfos_NodesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_graph_5freplication_2eproto_getter, &descriptor_table_graph_5freplication_2eproto_once,
      file_level_metadata_graph_5freplication_2eproto[3]);
}

// ===================================================================

class RaftNodeInfos::_Internal {
 public:
};

RaftNodeInfos::RaftNodeInfos(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &RaftNodeInfos::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:meta.RaftNodeInfos)
}
RaftNodeInfos::RaftNodeInfos(const RaftNodeInfos& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RaftNodeInfos* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.nodes_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
  // @@protoc_insertion_point(copy_constructor:meta.RaftNodeInfos)
}

inline void RaftNodeInfos::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.nodes_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RaftNodeInfos::~RaftNodeInfos() {
  // @@protoc_insertion_point(destructor:meta.RaftNodeInfos)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void RaftNodeInfos::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.nodes_.Destruct();
  _impl_.nodes_.~MapField();
}

void RaftNodeInfos::ArenaDtor(void* object) {
  RaftNodeInfos* _this = reinterpret_cast< RaftNodeInfos* >(object);
  _this->_impl_.nodes_.Destruct();
}
void RaftNodeInfos::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RaftNodeInfos::Clear() {
// @@protoc_insertion_point(message_clear_start:meta.RaftNodeInfos)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nodes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RaftNodeInfos::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<uint64, .meta.RaftNodeInfo> nodes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.nodes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RaftNodeInfos::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:meta.RaftNodeInfos)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<uint64, .meta.RaftNodeInfo> nodes = 1;
  if (!this->_internal_nodes().empty()) {
    using MapType = ::_pb::Map<uint64_t, ::meta::RaftNodeInfo>;
    using WireHelper = RaftNodeInfos_NodesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_nodes();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meta.RaftNodeInfos)
  return target;
}

size_t RaftNodeInfos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:meta.RaftNodeInfos)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint64, .meta.RaftNodeInfo> nodes = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_nodes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >::const_iterator
      it = this->_internal_nodes().begin();
      it != this->_internal_nodes().end(); ++it) {
    total_size += RaftNodeInfos_NodesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RaftNodeInfos::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RaftNodeInfos::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RaftNodeInfos::GetClassData() const { return &_class_data_; }


void RaftNodeInfos::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RaftNodeInfos*>(&to_msg);
  auto& from = static_cast<const RaftNodeInfos&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meta.RaftNodeInfos)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.nodes_.MergeFrom(from._impl_.nodes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RaftNodeInfos::CopyFrom(const RaftNodeInfos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meta.RaftNodeInfos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RaftNodeInfos::IsInitialized() const {
  return true;
}

void RaftNodeInfos::InternalSwap(RaftNodeInfos* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.nodes_.InternalSwap(&other->_impl_.nodes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RaftNodeInfos::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_graph_5freplication_2eproto_getter, &descriptor_table_graph_5freplication_2eproto_once,
      file_level_metadata_graph_5freplication_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace meta
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::meta::RaftRequest*
Arena::CreateMaybeMessage< ::meta::RaftRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meta::RaftRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::meta::RaftMessage*
Arena::CreateMaybeMessage< ::meta::RaftMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meta::RaftMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::meta::RaftNodeInfo*
Arena::CreateMaybeMessage< ::meta::RaftNodeInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meta::RaftNodeInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::meta::RaftNodeInfos_NodesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::meta::RaftNodeInfos_NodesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meta::RaftNodeInfos_NodesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::meta::RaftNodeInfos*
Arena::CreateMaybeMessage< ::meta::RaftNodeInfos >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meta::RaftNodeInfos >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
