// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph_replication.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_graph_5freplication_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_graph_5freplication_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "raft.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_graph_5freplication_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_graph_5freplication_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_graph_5freplication_2eproto;
namespace meta {
class RaftMessage;
struct RaftMessageDefaultTypeInternal;
extern RaftMessageDefaultTypeInternal _RaftMessage_default_instance_;
class RaftNodeInfo;
struct RaftNodeInfoDefaultTypeInternal;
extern RaftNodeInfoDefaultTypeInternal _RaftNodeInfo_default_instance_;
class RaftNodeInfos;
struct RaftNodeInfosDefaultTypeInternal;
extern RaftNodeInfosDefaultTypeInternal _RaftNodeInfos_default_instance_;
class RaftNodeInfos_NodesEntry_DoNotUse;
struct RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal;
extern RaftNodeInfos_NodesEntry_DoNotUseDefaultTypeInternal _RaftNodeInfos_NodesEntry_DoNotUse_default_instance_;
class RaftRequest;
struct RaftRequestDefaultTypeInternal;
extern RaftRequestDefaultTypeInternal _RaftRequest_default_instance_;
}  // namespace meta
PROTOBUF_NAMESPACE_OPEN
template<> ::meta::RaftMessage* Arena::CreateMaybeMessage<::meta::RaftMessage>(Arena*);
template<> ::meta::RaftNodeInfo* Arena::CreateMaybeMessage<::meta::RaftNodeInfo>(Arena*);
template<> ::meta::RaftNodeInfos* Arena::CreateMaybeMessage<::meta::RaftNodeInfos>(Arena*);
template<> ::meta::RaftNodeInfos_NodesEntry_DoNotUse* Arena::CreateMaybeMessage<::meta::RaftNodeInfos_NodesEntry_DoNotUse>(Arena*);
template<> ::meta::RaftRequest* Arena::CreateMaybeMessage<::meta::RaftRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace meta {

enum WriteBatchKind : int {
  UNKNOWN = 0,
  GRAPH_WRITE = 1,
  ID_GENERATOR = 2,
  GRAPH_INDEX_DDL = 3,
  WriteBatchKind_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  WriteBatchKind_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool WriteBatchKind_IsValid(int value);
constexpr WriteBatchKind WriteBatchKind_MIN = UNKNOWN;
constexpr WriteBatchKind WriteBatchKind_MAX = GRAPH_INDEX_DDL;
constexpr int WriteBatchKind_ARRAYSIZE = WriteBatchKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* WriteBatchKind_descriptor();
template<typename T>
inline const std::string& WriteBatchKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, WriteBatchKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function WriteBatchKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    WriteBatchKind_descriptor(), enum_t_value);
}
inline bool WriteBatchKind_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WriteBatchKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<WriteBatchKind>(
    WriteBatchKind_descriptor(), name, value);
}
// ===================================================================

class RaftRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:meta.RaftRequest) */ {
 public:
  inline RaftRequest() : RaftRequest(nullptr) {}
  ~RaftRequest() override;
  explicit PROTOBUF_CONSTEXPR RaftRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftRequest(const RaftRequest& from);
  RaftRequest(RaftRequest&& from) noexcept
    : RaftRequest() {
    *this = ::std::move(from);
  }

  inline RaftRequest& operator=(const RaftRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftRequest& operator=(RaftRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftRequest* internal_default_instance() {
    return reinterpret_cast<const RaftRequest*>(
               &_RaftRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RaftRequest& a, RaftRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftRequest& from) {
    RaftRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meta.RaftRequest";
  }
  protected:
  explicit RaftRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWbDataFieldNumber = 3,
    kIdFieldNumber = 1,
    kWbKindFieldNumber = 2,
  };
  // bytes wb_data = 3;
  void clear_wb_data();
  const std::string& wb_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wb_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wb_data();
  PROTOBUF_NODISCARD std::string* release_wb_data();
  void set_allocated_wb_data(std::string* wb_data);
  private:
  const std::string& _internal_wb_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wb_data(const std::string& value);
  std::string* _internal_mutable_wb_data();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // .meta.WriteBatchKind wb_kind = 2;
  void clear_wb_kind();
  ::meta::WriteBatchKind wb_kind() const;
  void set_wb_kind(::meta::WriteBatchKind value);
  private:
  ::meta::WriteBatchKind _internal_wb_kind() const;
  void _internal_set_wb_kind(::meta::WriteBatchKind value);
  public:

  // @@protoc_insertion_point(class_scope:meta.RaftRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wb_data_;
    uint64_t id_;
    int wb_kind_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5freplication_2eproto;
};
// -------------------------------------------------------------------

class RaftMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:meta.RaftMessage) */ {
 public:
  inline RaftMessage() : RaftMessage(nullptr) {}
  ~RaftMessage() override;
  explicit PROTOBUF_CONSTEXPR RaftMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftMessage(const RaftMessage& from);
  RaftMessage(RaftMessage&& from) noexcept
    : RaftMessage() {
    *this = ::std::move(from);
  }

  inline RaftMessage& operator=(const RaftMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftMessage& operator=(RaftMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftMessage* internal_default_instance() {
    return reinterpret_cast<const RaftMessage*>(
               &_RaftMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RaftMessage& a, RaftMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftMessage& from) {
    RaftMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meta.RaftMessage";
  }
  protected:
  explicit RaftMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGraphFieldNumber = 1,
    kMessageFieldNumber = 2,
  };
  // string graph = 1;
  void clear_graph();
  const std::string& graph() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_graph(ArgT0&& arg0, ArgT... args);
  std::string* mutable_graph();
  PROTOBUF_NODISCARD std::string* release_graph();
  void set_allocated_graph(std::string* graph);
  private:
  const std::string& _internal_graph() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_graph(const std::string& value);
  std::string* _internal_mutable_graph();
  public:

  // .raftpb.Message message = 2;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const ::raftpb::Message& message() const;
  PROTOBUF_NODISCARD ::raftpb::Message* release_message();
  ::raftpb::Message* mutable_message();
  void set_allocated_message(::raftpb::Message* message);
  private:
  const ::raftpb::Message& _internal_message() const;
  ::raftpb::Message* _internal_mutable_message();
  public:
  void unsafe_arena_set_allocated_message(
      ::raftpb::Message* message);
  ::raftpb::Message* unsafe_arena_release_message();

  // @@protoc_insertion_point(class_scope:meta.RaftMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr graph_;
    ::raftpb::Message* message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5freplication_2eproto;
};
// -------------------------------------------------------------------

class RaftNodeInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:meta.RaftNodeInfo) */ {
 public:
  inline RaftNodeInfo() : RaftNodeInfo(nullptr) {}
  ~RaftNodeInfo() override;
  explicit PROTOBUF_CONSTEXPR RaftNodeInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftNodeInfo(const RaftNodeInfo& from);
  RaftNodeInfo(RaftNodeInfo&& from) noexcept
    : RaftNodeInfo() {
    *this = ::std::move(from);
  }

  inline RaftNodeInfo& operator=(const RaftNodeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftNodeInfo& operator=(RaftNodeInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftNodeInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftNodeInfo* internal_default_instance() {
    return reinterpret_cast<const RaftNodeInfo*>(
               &_RaftNodeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RaftNodeInfo& a, RaftNodeInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftNodeInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftNodeInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftNodeInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftNodeInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftNodeInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftNodeInfo& from) {
    RaftNodeInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftNodeInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meta.RaftNodeInfo";
  }
  protected:
  explicit RaftNodeInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 2,
    kGraphFieldNumber = 7,
    kNodeIdFieldNumber = 1,
    kBoltPortFieldNumber = 3,
    kRaftPoftFieldNumber = 4,
    kIsLeaderFieldNumber = 5,
    kIsLearnerFieldNumber = 6,
  };
  // string ip = 2;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // string graph = 7;
  void clear_graph();
  const std::string& graph() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_graph(ArgT0&& arg0, ArgT... args);
  std::string* mutable_graph();
  PROTOBUF_NODISCARD std::string* release_graph();
  void set_allocated_graph(std::string* graph);
  private:
  const std::string& _internal_graph() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_graph(const std::string& value);
  std::string* _internal_mutable_graph();
  public:

  // uint64 node_id = 1;
  void clear_node_id();
  uint64_t node_id() const;
  void set_node_id(uint64_t value);
  private:
  uint64_t _internal_node_id() const;
  void _internal_set_node_id(uint64_t value);
  public:

  // int32 bolt_port = 3;
  void clear_bolt_port();
  int32_t bolt_port() const;
  void set_bolt_port(int32_t value);
  private:
  int32_t _internal_bolt_port() const;
  void _internal_set_bolt_port(int32_t value);
  public:

  // int32 raft_poft = 4;
  void clear_raft_poft();
  int32_t raft_poft() const;
  void set_raft_poft(int32_t value);
  private:
  int32_t _internal_raft_poft() const;
  void _internal_set_raft_poft(int32_t value);
  public:

  // bool is_leader = 5;
  void clear_is_leader();
  bool is_leader() const;
  void set_is_leader(bool value);
  private:
  bool _internal_is_leader() const;
  void _internal_set_is_leader(bool value);
  public:

  // bool is_learner = 6;
  void clear_is_learner();
  bool is_learner() const;
  void set_is_learner(bool value);
  private:
  bool _internal_is_learner() const;
  void _internal_set_is_learner(bool value);
  public:

  // @@protoc_insertion_point(class_scope:meta.RaftNodeInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr graph_;
    uint64_t node_id_;
    int32_t bolt_port_;
    int32_t raft_poft_;
    bool is_leader_;
    bool is_learner_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5freplication_2eproto;
};
// -------------------------------------------------------------------

class RaftNodeInfos_NodesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<RaftNodeInfos_NodesEntry_DoNotUse, 
    uint64_t, ::meta::RaftNodeInfo,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<RaftNodeInfos_NodesEntry_DoNotUse, 
    uint64_t, ::meta::RaftNodeInfo,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  RaftNodeInfos_NodesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR RaftNodeInfos_NodesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit RaftNodeInfos_NodesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const RaftNodeInfos_NodesEntry_DoNotUse& other);
  static const RaftNodeInfos_NodesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const RaftNodeInfos_NodesEntry_DoNotUse*>(&_RaftNodeInfos_NodesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_graph_5freplication_2eproto;
};

// -------------------------------------------------------------------

class RaftNodeInfos final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:meta.RaftNodeInfos) */ {
 public:
  inline RaftNodeInfos() : RaftNodeInfos(nullptr) {}
  ~RaftNodeInfos() override;
  explicit PROTOBUF_CONSTEXPR RaftNodeInfos(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftNodeInfos(const RaftNodeInfos& from);
  RaftNodeInfos(RaftNodeInfos&& from) noexcept
    : RaftNodeInfos() {
    *this = ::std::move(from);
  }

  inline RaftNodeInfos& operator=(const RaftNodeInfos& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftNodeInfos& operator=(RaftNodeInfos&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftNodeInfos& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftNodeInfos* internal_default_instance() {
    return reinterpret_cast<const RaftNodeInfos*>(
               &_RaftNodeInfos_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RaftNodeInfos& a, RaftNodeInfos& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftNodeInfos* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftNodeInfos* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftNodeInfos* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftNodeInfos>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftNodeInfos& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftNodeInfos& from) {
    RaftNodeInfos::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftNodeInfos* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meta.RaftNodeInfos";
  }
  protected:
  explicit RaftNodeInfos(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kNodesFieldNumber = 1,
  };
  // map<uint64, .meta.RaftNodeInfo> nodes = 1;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;
  public:
  void clear_nodes();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >&
      _internal_nodes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >*
      _internal_mutable_nodes();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >&
      nodes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >*
      mutable_nodes();

  // @@protoc_insertion_point(class_scope:meta.RaftNodeInfos)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        RaftNodeInfos_NodesEntry_DoNotUse,
        uint64_t, ::meta::RaftNodeInfo,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> nodes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_graph_5freplication_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RaftRequest

// uint64 id = 1;
inline void RaftRequest::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t RaftRequest::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t RaftRequest::id() const {
  // @@protoc_insertion_point(field_get:meta.RaftRequest.id)
  return _internal_id();
}
inline void RaftRequest::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void RaftRequest::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:meta.RaftRequest.id)
}

// .meta.WriteBatchKind wb_kind = 2;
inline void RaftRequest::clear_wb_kind() {
  _impl_.wb_kind_ = 0;
}
inline ::meta::WriteBatchKind RaftRequest::_internal_wb_kind() const {
  return static_cast< ::meta::WriteBatchKind >(_impl_.wb_kind_);
}
inline ::meta::WriteBatchKind RaftRequest::wb_kind() const {
  // @@protoc_insertion_point(field_get:meta.RaftRequest.wb_kind)
  return _internal_wb_kind();
}
inline void RaftRequest::_internal_set_wb_kind(::meta::WriteBatchKind value) {
  
  _impl_.wb_kind_ = value;
}
inline void RaftRequest::set_wb_kind(::meta::WriteBatchKind value) {
  _internal_set_wb_kind(value);
  // @@protoc_insertion_point(field_set:meta.RaftRequest.wb_kind)
}

// bytes wb_data = 3;
inline void RaftRequest::clear_wb_data() {
  _impl_.wb_data_.ClearToEmpty();
}
inline const std::string& RaftRequest::wb_data() const {
  // @@protoc_insertion_point(field_get:meta.RaftRequest.wb_data)
  return _internal_wb_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftRequest::set_wb_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.wb_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meta.RaftRequest.wb_data)
}
inline std::string* RaftRequest::mutable_wb_data() {
  std::string* _s = _internal_mutable_wb_data();
  // @@protoc_insertion_point(field_mutable:meta.RaftRequest.wb_data)
  return _s;
}
inline const std::string& RaftRequest::_internal_wb_data() const {
  return _impl_.wb_data_.Get();
}
inline void RaftRequest::_internal_set_wb_data(const std::string& value) {
  
  _impl_.wb_data_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftRequest::_internal_mutable_wb_data() {
  
  return _impl_.wb_data_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftRequest::release_wb_data() {
  // @@protoc_insertion_point(field_release:meta.RaftRequest.wb_data)
  return _impl_.wb_data_.Release();
}
inline void RaftRequest::set_allocated_wb_data(std::string* wb_data) {
  if (wb_data != nullptr) {
    
  } else {
    
  }
  _impl_.wb_data_.SetAllocated(wb_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.wb_data_.IsDefault()) {
    _impl_.wb_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:meta.RaftRequest.wb_data)
}

// -------------------------------------------------------------------

// RaftMessage

// string graph = 1;
inline void RaftMessage::clear_graph() {
  _impl_.graph_.ClearToEmpty();
}
inline const std::string& RaftMessage::graph() const {
  // @@protoc_insertion_point(field_get:meta.RaftMessage.graph)
  return _internal_graph();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftMessage::set_graph(ArgT0&& arg0, ArgT... args) {
 
 _impl_.graph_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meta.RaftMessage.graph)
}
inline std::string* RaftMessage::mutable_graph() {
  std::string* _s = _internal_mutable_graph();
  // @@protoc_insertion_point(field_mutable:meta.RaftMessage.graph)
  return _s;
}
inline const std::string& RaftMessage::_internal_graph() const {
  return _impl_.graph_.Get();
}
inline void RaftMessage::_internal_set_graph(const std::string& value) {
  
  _impl_.graph_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftMessage::_internal_mutable_graph() {
  
  return _impl_.graph_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftMessage::release_graph() {
  // @@protoc_insertion_point(field_release:meta.RaftMessage.graph)
  return _impl_.graph_.Release();
}
inline void RaftMessage::set_allocated_graph(std::string* graph) {
  if (graph != nullptr) {
    
  } else {
    
  }
  _impl_.graph_.SetAllocated(graph, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.graph_.IsDefault()) {
    _impl_.graph_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:meta.RaftMessage.graph)
}

// .raftpb.Message message = 2;
inline bool RaftMessage::_internal_has_message() const {
  return this != internal_default_instance() && _impl_.message_ != nullptr;
}
inline bool RaftMessage::has_message() const {
  return _internal_has_message();
}
inline const ::raftpb::Message& RaftMessage::_internal_message() const {
  const ::raftpb::Message* p = _impl_.message_;
  return p != nullptr ? *p : reinterpret_cast<const ::raftpb::Message&>(
      ::raftpb::_Message_default_instance_);
}
inline const ::raftpb::Message& RaftMessage::message() const {
  // @@protoc_insertion_point(field_get:meta.RaftMessage.message)
  return _internal_message();
}
inline void RaftMessage::unsafe_arena_set_allocated_message(
    ::raftpb::Message* message) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.message_);
  }
  _impl_.message_ = message;
  if (message) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meta.RaftMessage.message)
}
inline ::raftpb::Message* RaftMessage::release_message() {
  
  ::raftpb::Message* temp = _impl_.message_;
  _impl_.message_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::raftpb::Message* RaftMessage::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_release:meta.RaftMessage.message)
  
  ::raftpb::Message* temp = _impl_.message_;
  _impl_.message_ = nullptr;
  return temp;
}
inline ::raftpb::Message* RaftMessage::_internal_mutable_message() {
  
  if (_impl_.message_ == nullptr) {
    auto* p = CreateMaybeMessage<::raftpb::Message>(GetArenaForAllocation());
    _impl_.message_ = p;
  }
  return _impl_.message_;
}
inline ::raftpb::Message* RaftMessage::mutable_message() {
  ::raftpb::Message* _msg = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:meta.RaftMessage.message)
  return _msg;
}
inline void RaftMessage::set_allocated_message(::raftpb::Message* message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.message_);
  }
  if (message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(message));
    if (message_arena != submessage_arena) {
      message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.message_ = message;
  // @@protoc_insertion_point(field_set_allocated:meta.RaftMessage.message)
}

// -------------------------------------------------------------------

// RaftNodeInfo

// uint64 node_id = 1;
inline void RaftNodeInfo::clear_node_id() {
  _impl_.node_id_ = uint64_t{0u};
}
inline uint64_t RaftNodeInfo::_internal_node_id() const {
  return _impl_.node_id_;
}
inline uint64_t RaftNodeInfo::node_id() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.node_id)
  return _internal_node_id();
}
inline void RaftNodeInfo::_internal_set_node_id(uint64_t value) {
  
  _impl_.node_id_ = value;
}
inline void RaftNodeInfo::set_node_id(uint64_t value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.node_id)
}

// string ip = 2;
inline void RaftNodeInfo::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& RaftNodeInfo::ip() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftNodeInfo::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.ip)
}
inline std::string* RaftNodeInfo::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:meta.RaftNodeInfo.ip)
  return _s;
}
inline const std::string& RaftNodeInfo::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void RaftNodeInfo::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftNodeInfo::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftNodeInfo::release_ip() {
  // @@protoc_insertion_point(field_release:meta.RaftNodeInfo.ip)
  return _impl_.ip_.Release();
}
inline void RaftNodeInfo::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:meta.RaftNodeInfo.ip)
}

// int32 bolt_port = 3;
inline void RaftNodeInfo::clear_bolt_port() {
  _impl_.bolt_port_ = 0;
}
inline int32_t RaftNodeInfo::_internal_bolt_port() const {
  return _impl_.bolt_port_;
}
inline int32_t RaftNodeInfo::bolt_port() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.bolt_port)
  return _internal_bolt_port();
}
inline void RaftNodeInfo::_internal_set_bolt_port(int32_t value) {
  
  _impl_.bolt_port_ = value;
}
inline void RaftNodeInfo::set_bolt_port(int32_t value) {
  _internal_set_bolt_port(value);
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.bolt_port)
}

// int32 raft_poft = 4;
inline void RaftNodeInfo::clear_raft_poft() {
  _impl_.raft_poft_ = 0;
}
inline int32_t RaftNodeInfo::_internal_raft_poft() const {
  return _impl_.raft_poft_;
}
inline int32_t RaftNodeInfo::raft_poft() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.raft_poft)
  return _internal_raft_poft();
}
inline void RaftNodeInfo::_internal_set_raft_poft(int32_t value) {
  
  _impl_.raft_poft_ = value;
}
inline void RaftNodeInfo::set_raft_poft(int32_t value) {
  _internal_set_raft_poft(value);
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.raft_poft)
}

// bool is_leader = 5;
inline void RaftNodeInfo::clear_is_leader() {
  _impl_.is_leader_ = false;
}
inline bool RaftNodeInfo::_internal_is_leader() const {
  return _impl_.is_leader_;
}
inline bool RaftNodeInfo::is_leader() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.is_leader)
  return _internal_is_leader();
}
inline void RaftNodeInfo::_internal_set_is_leader(bool value) {
  
  _impl_.is_leader_ = value;
}
inline void RaftNodeInfo::set_is_leader(bool value) {
  _internal_set_is_leader(value);
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.is_leader)
}

// bool is_learner = 6;
inline void RaftNodeInfo::clear_is_learner() {
  _impl_.is_learner_ = false;
}
inline bool RaftNodeInfo::_internal_is_learner() const {
  return _impl_.is_learner_;
}
inline bool RaftNodeInfo::is_learner() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.is_learner)
  return _internal_is_learner();
}
inline void RaftNodeInfo::_internal_set_is_learner(bool value) {
  
  _impl_.is_learner_ = value;
}
inline void RaftNodeInfo::set_is_learner(bool value) {
  _internal_set_is_learner(value);
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.is_learner)
}

// string graph = 7;
inline void RaftNodeInfo::clear_graph() {
  _impl_.graph_.ClearToEmpty();
}
inline const std::string& RaftNodeInfo::graph() const {
  // @@protoc_insertion_point(field_get:meta.RaftNodeInfo.graph)
  return _internal_graph();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftNodeInfo::set_graph(ArgT0&& arg0, ArgT... args) {
 
 _impl_.graph_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meta.RaftNodeInfo.graph)
}
inline std::string* RaftNodeInfo::mutable_graph() {
  std::string* _s = _internal_mutable_graph();
  // @@protoc_insertion_point(field_mutable:meta.RaftNodeInfo.graph)
  return _s;
}
inline const std::string& RaftNodeInfo::_internal_graph() const {
  return _impl_.graph_.Get();
}
inline void RaftNodeInfo::_internal_set_graph(const std::string& value) {
  
  _impl_.graph_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftNodeInfo::_internal_mutable_graph() {
  
  return _impl_.graph_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftNodeInfo::release_graph() {
  // @@protoc_insertion_point(field_release:meta.RaftNodeInfo.graph)
  return _impl_.graph_.Release();
}
inline void RaftNodeInfo::set_allocated_graph(std::string* graph) {
  if (graph != nullptr) {
    
  } else {
    
  }
  _impl_.graph_.SetAllocated(graph, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.graph_.IsDefault()) {
    _impl_.graph_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:meta.RaftNodeInfo.graph)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RaftNodeInfos

// map<uint64, .meta.RaftNodeInfo> nodes = 1;
inline int RaftNodeInfos::_internal_nodes_size() const {
  return _impl_.nodes_.size();
}
inline int RaftNodeInfos::nodes_size() const {
  return _internal_nodes_size();
}
inline void RaftNodeInfos::clear_nodes() {
  _impl_.nodes_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >&
RaftNodeInfos::_internal_nodes() const {
  return _impl_.nodes_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >&
RaftNodeInfos::nodes() const {
  // @@protoc_insertion_point(field_map:meta.RaftNodeInfos.nodes)
  return _internal_nodes();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >*
RaftNodeInfos::_internal_mutable_nodes() {
  return _impl_.nodes_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::meta::RaftNodeInfo >*
RaftNodeInfos::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_map:meta.RaftNodeInfos.nodes)
  return _internal_mutable_nodes();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace meta

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::meta::WriteBatchKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::meta::WriteBatchKind>() {
  return ::meta::WriteBatchKind_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_graph_5freplication_2eproto
